# Generated by Django 3.1.2 on 2020-12-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20201129_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[('Sport', 'Sport'), ('World', 'World'), ('Covid', 'Covid'), ('Business', 'Business')], max_length=200),
        ),
    ]
