# Generated by Django 3.1.2 on 2020-12-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20201203_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[('Sport', 'sport'), ('World', 'world'), ('Covid', 'covid'), ('Business', 'business')], max_length=200),
        ),
    ]
